encoder:
  name: bert-base-multilingual-cased
  model: AutoModel
  tokenizer: AutoTokenizer

decoder:
  name: ckiplab/gpt2-base-chinese
  model: GPT2LMHeadModel
  body: transformer
  head: lm_head
  tokenizer: BertTokenizerFast
  embed_dim: 768
  bos_token: "[CLS]"
  decoder_start_token_id: 101
  need_prefix: false

graft_module_config:
  num_enc_layer: 2
  num_dec_layer: 2