defaults:
  - encoder: bert
  - decoder: gpt
  - data: default
  - _self_

graft_module_config:
  num_enc_layer: 2
  num_dec_layer: 2

train_config:
  lr: 0.00005
  batch_size: 4
  weight_decay: 0.01
  num_train_epochs: 100
  gradient_accumulation_steps: 32
