model:
  encoder_name_or_path: ''
  decoder_name_or_path: ''
---
data:
  dataset_path: ''
  train_data_path: ''
  eval_data_path: ''
  max_seq_length: 
---
training:
  learning_rate: 1e5
  num_train_epochs: 3
  seed: 42
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  gradient_accumulation_steps: 1
  output_dir: ''
  logging_dir: ''
  max_train_steps: None
