name: kykim/gpt3-kor-small_based_on_gpt2
model: GPT2LMHeadModel
body: transformer
head: lm_head
tokenizer: BertTokenizerFast
embed_dim: 768
bos_token: "[CLS]"
decoder_start_token_id: 2
need_prefix: False
